version: '3'

services:

  db:
    image: postgres
    env_file: ./web_application/web.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS= -Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always

  web:
    build: ./web_application
    env_file: ./web_application/web.env
    command: /code/run_web.sh
    volumes:
      - ./web_application:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
      - elastic

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./web_application/static_root:/code/static_root
      - ./web_application/media:/code/media
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  esdata2:
