version: '3'

services:

  db:
    image: postgres
    env_file: ./web_application/web.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./elastic_data:/usr/share/elasticsearch/data
#    ports:
#      - "9201:9200"

  web:
    build: ./web_application
    env_file: ./web_application/web.env
    command: /code/run_web.sh
    volumes:
      - ./web_application:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
      - elastic

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./web_application/static_root:/code/static_root
      - ./web_application/media:/code/media
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - web
