# Generated by Django 2.2.2 on 2019-06-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.TextField(default=False),
        ),
    ]
