# Generated by Django 2.2.2 on 2019-07-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_book_literary_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='drive_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='book',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='char',
            field=models.ManyToManyField(blank=True, to='catalog.Character'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='character',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Character'),
        ),
    ]
