# Generated by Django 2.2.2 on 2019-07-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190706_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='book',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='character',
        ),
    ]
