# Generated by Django 2.2.2 on 2019-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190714_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
