# Generated by Django 2.2.2 on 2019-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_review_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
