# Generated by Django 2.2.2 on 2019-07-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_review_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('link', models.URLField(max_length=255)),
                ('photo_origin', models.URLField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='authors')),
                ('biography', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, default=111, on_delete=django.db.models.deletion.CASCADE, to='catalog.Author'),
            preserve_default=False,
        ),
    ]
