# Generated by Django 2.2.2 on 2019-08-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='books_count',
            new_name='qcount',
        ),
    ]
