# Generated by Django 2.2.2 on 2019-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20190803_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='qcount',
            field=models.IntegerField(default=0),
        ),
    ]
