# Generated by Django 2.2.2 on 2019-06-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190630_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('aliases', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('source', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='edition_language',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('original', models.URLField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Character')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='char',
            field=models.ManyToManyField(to='catalog.Character'),
        ),
    ]
