# Generated by Django 2.2.2 on 2019-07-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190706_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Photo'),
        ),
        migrations.AddField(
            model_name='character',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Photo'),
        ),
    ]
